### ISSUE TITLE
String variables not correctly resolved

### ISSUE THREAD

**Issue by sebastiansandqvist** [tivac/mithril-objectify#49]
I have the following component which works without `mopt` enabled, but is broken with `mopt`:

```js
const NEWEST = 'Newest first';
const VOTES = 'Most votes';
const SortToggle = {
	view({ attrs }) {
		return (
			m('.SortToggle',
				m('.SortToggle-option', { onclick() { attrs.sortBy(NEWEST); } }, NEWEST),
				m('.SortToggle-option', { onclick() { attrs.sortBy(MOST_VOTES); } }, MOST_VOTES)
			)
		);

	}
};
```

It works fine using `mopt` if I inline the string constants, like this:

```js
const NEWEST = 'Newest first';
const VOTES = 'Most votes';
const SortToggle = {
	view({ attrs }) {
		return (
			m('.SortToggle',
				m('.SortToggle-option', { onclick() { attrs.sortBy(NEWEST); } }, 'Newest first'),
				m('.SortToggle-option', { onclick() { attrs.sortBy(MOST_VOTES); } }, 'Most votes')
			)
		);

	}
};
```

**Comment by tivac** [comment]
Thanks for the report!

Can you provide examples of the broken output on a minimal repro? That'd be a huge help for figuring out the issue here!

**Comment by sebastiansandqvist** [comment]
Sure, here you go: https://github.com/sebastiansandqvist/mopt-bug-repro

**Comment by sebastiansandqvist** [comment]
The issue appears to only happen if both of the following conditions are met:

- a variable is being used rather than a literal as the text node
- the component contains a second argument for attrs

**Comment by tivac** [comment]
`mithril-objectify` isn't compatible with the `rewrite` branch of mithril.

See https://github.com/lhorie/mithril.js/issues/1086 for why. There is a [`rewrite`](https://github.com/tivac/mithril-objectify/tree/rewrite) branch where I was working on support but I've held off on further work because there still isn't a great way to support the underlying vnode structure from a static analysis tool.
